// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"database/sql"
	"time"
)

type Reading struct {
	ID         int64          `json:"id"`
	SourceID   string         `json:"source_id"`
	MetricType string         `json:"metric_type"`
	Value      float64        `json:"value"`
	Unit       string         `json:"unit"`
	RecordedAt time.Time      `json:"recorded_at"`
	ReceivedAt time.Time      `json:"received_at"`
	Metadata   sql.NullString `json:"metadata"`
}

type Source struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	ApiKey    string    `json:"api_key"`
	Config    string    `json:"config"`
	CreatedAt time.Time `json:"created_at"`
}