// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: readings.sql

package storage

import (
	"context"
	"database/sql"
	"time"
)

const getLatestReadingsByMetric = `-- name: GetLatestReadingsByMetric :many
WITH latest AS (
    SELECT source_id, MAX(recorded_at) AS max_at
    FROM readings
    WHERE metric_type = ?1
    GROUP BY source_id
)
SELECT r.id, r.source_id, r.metric_type, r.value, r.unit, r.recorded_at, r.received_at, r.metadata
FROM readings r
JOIN latest ON r.source_id = latest.source_id AND r.recorded_at = latest.max_at
WHERE r.metric_type = ?1
`

// Returns the most recent reading per source for a given metric type.
func (q *Queries) GetLatestReadingsByMetric(ctx context.Context, metricType string) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, getLatestReadingsByMetric, metricType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.MetricType,
			&i.Value,
			&i.Unit,
			&i.RecordedAt,
			&i.ReceivedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadingsInRange = `-- name: GetReadingsInRange :many
SELECT id, source_id, metric_type, value, unit, recorded_at, received_at, metadata FROM readings
WHERE source_id   = ?1
  AND metric_type = ?2
  AND recorded_at >= ?3
  AND recorded_at <= ?4
ORDER BY recorded_at ASC
`

type GetReadingsInRangeParams struct {
	SourceID   string    `json:"source_id"`
	MetricType string    `json:"metric_type"`
	FromTime   time.Time `json:"from_time"`
	ToTime     time.Time `json:"to_time"`
}

func (q *Queries) GetReadingsInRange(ctx context.Context, arg GetReadingsInRangeParams) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, getReadingsInRange,
		arg.SourceID,
		arg.MetricType,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.MetricType,
			&i.Value,
			&i.Unit,
			&i.RecordedAt,
			&i.ReceivedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReading = `-- name: InsertReading :exec
INSERT INTO readings (source_id, metric_type, value, unit, recorded_at, metadata)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertReadingParams struct {
	SourceID   string         `json:"source_id"`
	MetricType string         `json:"metric_type"`
	Value      float64        `json:"value"`
	Unit       string         `json:"unit"`
	RecordedAt time.Time      `json:"recorded_at"`
	Metadata   sql.NullString `json:"metadata"`
}

func (q *Queries) InsertReading(ctx context.Context, arg InsertReadingParams) error {
	_, err := q.db.ExecContext(ctx, insertReading,
		arg.SourceID,
		arg.MetricType,
		arg.Value,
		arg.Unit,
		arg.RecordedAt,
		arg.Metadata,
	)
	return err
}
