// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sources.sql

package storage

import (
	"context"
)

const getSourceByAPIKey = `-- name: GetSourceByAPIKey :one
SELECT id, name, kind, api_key, config, created_at FROM sources WHERE api_key = ?
`

func (q *Queries) GetSourceByAPIKey(ctx context.Context, apiKey string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSourceByAPIKey, apiKey)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.ApiKey,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceByID = `-- name: GetSourceByID :one
SELECT id, name, kind, api_key, config, created_at FROM sources WHERE id = ?
`

func (q *Queries) GetSourceByID(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSourceByID, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.ApiKey,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const insertSource = `-- name: InsertSource :one
INSERT INTO sources (id, name, kind, api_key, config)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, kind, api_key, config, created_at
`

type InsertSourceParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Kind   string `json:"kind"`
	ApiKey string `json:"api_key"`
	Config string `json:"config"`
}

func (q *Queries) InsertSource(ctx context.Context, arg InsertSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, insertSource,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.ApiKey,
		arg.Config,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.ApiKey,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const listSources = `-- name: ListSources :many
SELECT id, name, kind, api_key, config, created_at FROM sources ORDER BY created_at ASC
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.ApiKey,
			&i.Config,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
